# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

# Path to your oh-my-zsh installation.
export ZSH="$HOME/.oh-my-zsh"
#export EDITOR="nvim"

if [[ "nvim" != $(ps -p $(ps -p $$ -o ppid=) o args= | awk '{print $1 }') ]]
then
    clear;neofetch | lolcat
fi

# Set name of the theme to load --- if set to "random", it will
# load a random theme each time oh-my-zsh is loaded, in which case,
# to know which specific one was loaded, run: echo $RANDOM_THEME
# See https://github.com/ohmyzsh/ohmyzsh/wiki/Themes
ZSH_THEME="robbyrussell"
plugins=(zsh-autosuggestions zsh-syntax-highlighting)

source $ZSH/oh-my-zsh.sh
alias ncat='neofetch | lolcat'
alias vrc="vim ~/.config/nvim/init.lua"
alias zrc="nvim ~/.zshrc"
alias rr="ranger"
alias q='exit'
alias h="htop"
alias g="gtop"
alias c='clear'
alias n='nvim'
alias v='vim'
alias ls='exa --color=always --group-directories-first --icons'  # all files and dirs
alias u='sudo pacman -Syyu'
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
[ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion

export PATH=$HOME/bin:/usr/local/bin:/sbin:/usr/sbin:/var/lib/snapd/snap/bin:/home/anurag/.local/bin:/home/anurag/.program:$PATH

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.

autoload -Uz compinit
compinit

kitty + complete setup zsh | source /dev/stdin

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh


[[ -s /home/anurag/.autojump/etc/profile.d/autojump.sh ]] && source /home/anurag/.autojump/etc/profile.d/autojump.sh
# Completion for kitty
autoload -U compinit && compinit -u

eval "$(starship init zsh)"

