lastupdatecheck: 0
recentrepos:
- /home/ew/.config/nvim
- /home/ew/repos/my-setup
- /home/ew/repos/Hyprland
- /home/ew/repos/RustPython
- /home/ew/repos/ytop
- /home/ew/repos/TempleOS
- /home/ew/rust
- /home/ew/repos/surf
- /home/ew/Downloads/dmenu-5.1
- /home/ew/repos/dmenu
- /home/ew/repos/firefox-gnome-theme
- /home/ew/repos/sd
- /home/ew/Projects/nautilus
- /home/ew/repos/dmenu-rs
- /home/ew/repos/paru
- /home/ew/ai/tesseractflow
- /home/ew/repos/swaylock-effects
- /home/ew/repos/void-packages
- /home/ew/repos/ps
- /home/ew/repos/garden-hyprland-dotfiles
- /home/ew/code/breakout
- /home/ew/repos/howto-lf-image-previews
- /home/ew/code/paru_pr
- /home/ew/temp/nvim
- /home/ew
- /home/ew/repos/hyprland-rs
startuppopupversion: 5
customcommandshistory:
- q
- echo hello
- git reset --hard
- b
- btop
- git remote -v
hidecommandlog: true
